### ISSUE TITLE
Determine list of package functions for initial launch

### ISSUE THREAD

**Issue by jacksonsj** [pepfar-datim/datimutils#1]
## Description
@jason-p-pickering @sam-bao - Please add any suggested functions to include in this package (what it should do, not a name suggestion) for its initial launch:

- login to DATIM using username and pw
- export dimension data/metadata (e.g., `categoryOptions`, `dataElements`, `organisationUnits`) from endpoint, and allow easy, `magrittr`-friendly filtering and field selection.
- Pull a SQL view
- perform basic query against Analytics API
- Export list of sites for supplied country id, specifying between facility and community
- Export list of mechanisms for supplied country id
- Export list of PSNUs (optional inclusion of _Military here), or any SNU level for supplied country id
- Export list of form-valid dataElements, categoryOptionCombos, and categoryOptions (classified by category) for supplied dataset and fiscal year and/or quarter. (HAS to link to the code list SQL View to make sure this list represents what is ACTUALLY valid in forms for a given dataset and year.)

## Acceptance criteria and must have scope
The goal is to accumulate upfront as many ideas for potential functions as are possible, and then to later convert these into epics or issues in our backlog.

## Stakeholders
Would be good to run this list past ICPI users as they seem to be the largest potential user base. These functions should also allow offload of any generic DATIM API interactions from `datapackr` and `datimvalidation`.

## Timeline
Goal is to complete first pass of this list by Aug 30, 2019.

**Comment by sam-bao** [comment]
Suggestions to be discussed:

- function(s) to convert column names between snake case (used in R code)/non-snake case (used by api)   
- function for retrying api when call is unsuccessful (e.g. datapackcommons::RetryApi)
- functions to validate/recode between names/ids/codes (e.g. datapackcommons::ValidateNameIdPairs)
- Functions (perhaps not exported) to to convert lists or other data structures to strings for API calls (e.g. datapackcommons::FormatForApi_Dimensions)
- Function to use DataValueSet endpoint
