### ISSUE TITLE
lexical error: invalid char in json text

### ISSUE THREAD

**Issue by augustinemalero** [pepfar-datim/datimutils#115]
Hi,
I have installed both datimvalidation and datimutils R packages for pepfar data validation purposes.  When I try to use the logintodatim function, however, I get the error `Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML> <html class="lo
                     (right here) ------^`

This is how I used it:  `loginToDATIM(base_url = "https://dev-de.datim.org/dhis-web-commons/security/login.action", username = "xxx", password = "xxxxxxx")`. The base url from the manual says I should use http://dev-de.datim.org which gives an error `Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: dev-de.datim.orgapi` 

With this error, I changed to the resolved URL which is https://dev-de.datim.org/dhis-web-commons/security/login.action but then faces the lexical error explained. I am stuck and cannot make any progress; any help would be appreciated. Just to add, I have an existing account in Datim.

Augustine

**Comment by jason-p-pickering** [comment]
Hi @augustinemalero 
This indicates that you have not logged into the server. The `base_url` variable should be `http:://dev-de.datim.org/` . The final forward slash is important. This was perhaps not super clear and we will try and improve this a bit to provide better user feedback.  Please let us know if this works!

**Comment by augustinemalero** [comment]
Hi Jason,

Thank you for your response, this did the trick!

Augustine
