### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by amacharia2017** [pepfar-datim/datimutils#122]
Hello 
How do I sought this error when using datimutils getDataValueSets but I get an Error
Error: parse error: premature EOF
                                       
                     (right here) ------^

**Comment by jason-p-pickering** [comment]
This is usually because you are not logged in, or your session has expired.  Use the function `loginToDATIM` with your credentials in order to login.

**Comment by amacharia2017** [comment]
Hello Jason,
Have already logged in and have pulled dataElements, orgUnits etc but when
it gets to dataValueSets for some dataset I get that error while for some
other dataset am able to get the values.
